export const mockHotels = [
  {
    id: '1',
    name: 'Dar Al-Sultan Heritage Hotel',
    nameAr: 'دار السلطان',
    city: 'Jerusalem',
    address: 'Muslim Quarter, Old City, Jerusalem',
    stars: 5,
    pricePerNight: 320,
    rating: 4.8,
    reviewCount: 412,
    description: 'Steps from the Al-Aqsa Mosque and the Church of the Holy Sepulchre, Dar Al-Sultan offers an unparalleled blend of Mamluk architecture and modern comfort. Experience the heart of Jerusalem from our rooftop terrace overlooking the ancient city.',
    amenities: ['WiFi', 'Rooftop Terrace', 'Restaurant', 'Room Service', 'Prayer Room', 'City View', 'Halal Kitchen'],
    images: ['https://images.unsplash.com/photo-1553653924-39b70295f8da?w=800', 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800'],
    featured: true,
    phone: '+972-2-6280-100',
    email: 'info@daralsultan.ps',
    policies: 'Check-in: 3:00 PM | Check-out: 12:00 PM | Free cancellation up to 48 hours before arrival.',
    rooms: [
      { id: 'r1', type: 'Standard Room', capacity: 2, bedType: 'Double', pricePerNight: 320, available: true },
      { id: 'r2', type: 'Deluxe Suite', capacity: 2, bedType: 'King', pricePerNight: 480, available: true },
      { id: 'r3', type: 'Family Room', capacity: 4, bedType: 'Two Queens', pricePerNight: 550, available: false },
    ],
  },
  {
    id: '2',
    name: 'Bethlehem Star Hotel',
    nameAr: 'فندق بيت لحم ستار',
    city: 'Bethlehem',
    address: 'Manger Square, Bethlehem, West Bank',
    stars: 4,
    pricePerNight: 180,
    rating: 4.6,
    reviewCount: 287,
    description: 'Located on historic Manger Square, our hotel offers stunning views of the Church of the Nativity. A perfect base for pilgrims and cultural travelers exploring the birthplace of Jesus Christ.',
    amenities: ['WiFi', 'Parking', 'Restaurant', 'Prayer Room', 'City View', 'Halal Kitchen', 'Garden'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
    featured: true,
    phone: '+972-2-2741-602',
    email: 'reservations@bethlehemstar.ps',
    policies: 'Check-in: 2:00 PM | Check-out: 11:00 AM | Free cancellation up to 24 hours before arrival.',
    rooms: [
      { id: 'r4', type: 'Standard Room', capacity: 2, bedType: 'Twin', pricePerNight: 180, available: true },
      { id: 'r5', type: 'Superior Room', capacity: 2, bedType: 'Double', pricePerNight: 220, available: true },
    ],
  },
  {
    id: '3',
    name: 'Nazareth Palace Hotel',
    nameAr: 'قصر الناصرة',
    city: 'Nazareth',
    address: 'Old City, Nazareth, Galilee',
    stars: 4,
    pricePerNight: 210,
    rating: 4.7,
    reviewCount: 198,
    description: 'An elegant boutique hotel nestled in a restored Ottoman-era building in the heart of Nazareth\'s Old City. Minutes from the Basilica of the Annunciation, we blend authentic Palestinian hospitality with refined luxury.',
    amenities: ['WiFi', 'Spa', 'Restaurant', 'Rooftop Terrace', 'City View', 'Halal Kitchen', 'Prayer Room'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
    featured: true,
    phone: '+972-4-6080-000',
    email: 'info@nazarethpalace.ps',
    policies: 'Check-in: 3:00 PM | Check-out: 12:00 PM | 48-hour cancellation policy.',
    rooms: [
      { id: 'r6', type: 'Classic Room', capacity: 2, bedType: 'Double', pricePerNight: 210, available: true },
      { id: 'r7', type: 'Deluxe Room', capacity: 2, bedType: 'King', pricePerNight: 280, available: true },
      { id: 'r8', type: 'Junior Suite', capacity: 3, bedType: 'King + Sofa', pricePerNight: 350, available: true },
    ],
  },
  {
    id: '4',
    name: 'Al-Khalil Grand Hotel',
    nameAr: 'فندق الخليل الكبير',
    city: 'Hebron',
    address: 'City Center, Hebron, West Bank',
    stars: 3,
    pricePerNight: 95,
    rating: 4.2,
    reviewCount: 134,
    description: 'Situated in the commercial heart of Hebron, Al-Khalil Grand offers comfortable accommodations near the Cave of Machpelah and the historic Glass Quarter. Ideal for business and heritage travelers alike.',
    amenities: ['WiFi', 'Parking', 'Restaurant', 'Prayer Room', 'Halal Kitchen'],
    images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800'],
    featured: false,
    phone: '+972-2-2221-234',
    email: 'contact@alkhalilgrand.ps',
    policies: 'Check-in: 2:00 PM | Check-out: 12:00 PM | Free cancellation up to 24 hours.',
    rooms: [
      { id: 'r9', type: 'Standard Room', capacity: 2, bedType: 'Twin', pricePerNight: 95, available: true },
      { id: 'r10', type: 'Double Room', capacity: 2, bedType: 'Double', pricePerNight: 120, available: true },
    ],
  },
  {
    id: '5',
    name: 'Jericho Oasis Resort',
    nameAr: 'منتجع أريحا الواحة',
    city: 'Jericho',
    address: 'Jericho Valley Road, Jericho',
    stars: 5,
    pricePerNight: 295,
    rating: 4.9,
    reviewCount: 321,
    description: 'Set in the world\'s oldest city near the Dead Sea and Wadi Qelt, Jericho Oasis Resort features lush gardens, a stunning pool, and panoramic views of the Jordan Valley. The lowest-elevation luxury hotel on Earth.',
    amenities: ['WiFi', 'Pool', 'Spa', 'Gym', 'Restaurant', 'Room Service', 'Parking', 'Garden', 'Prayer Room'],
    images: ['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800'],
    featured: true,
    phone: '+972-2-2321-000',
    email: 'reservations@jerichooasis.ps',
    policies: 'Check-in: 3:00 PM | Check-out: 1:00 PM | Free cancellation up to 72 hours.',
    rooms: [
      { id: 'r11', type: 'Garden View Room', capacity: 2, bedType: 'King', pricePerNight: 295, available: true },
      { id: 'r12', type: 'Pool Suite', capacity: 2, bedType: 'King', pricePerNight: 450, available: true },
      { id: 'r13', type: 'Family Bungalow', capacity: 5, bedType: 'Various', pricePerNight: 620, available: false },
    ],
  },
  {
    id: '6',
    name: 'Ramallah Cultural Hotel',
    nameAr: 'فندق رام الله الثقافي',
    city: 'Ramallah',
    address: 'Al-Manarah Square, Ramallah',
    stars: 4,
    pricePerNight: 155,
    rating: 4.4,
    reviewCount: 209,
    description: 'At the cultural pulse of modern Palestine, our hotel sits beside the vibrant Al-Manarah Square. Contemporary Palestinian art adorns every room. An ideal base for exploring Ramallah\'s thriving arts scene, restaurants, and galleries.',
    amenities: ['WiFi', 'Restaurant', 'Gym', 'Rooftop Terrace', 'Room Service', 'City View'],
    images: ['https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800'],
    featured: false,
    phone: '+972-2-2981-000',
    email: 'info@ramallahculturalhotel.ps',
    policies: 'Check-in: 2:00 PM | Check-out: 12:00 PM | 24-hour cancellation policy.',
    rooms: [
      { id: 'r14', type: 'Standard Room', capacity: 2, bedType: 'Double', pricePerNight: 155, available: true },
      { id: 'r15', type: 'Art Suite', capacity: 2, bedType: 'King', pricePerNight: 230, available: true },
    ],
  },
  {
    id: '7',
    name: 'Beit Sahour Shepherd\'s Inn',
    nameAr: 'نزل الراعي بيت ساحور',
    city: 'Bethlehem',
    address: 'Shepherd\'s Field Road, Beit Sahour',
    stars: 3,
    pricePerNight: 110,
    rating: 4.5,
    reviewCount: 156,
    description: 'Near the legendary Shepherd\'s Field where angels announced the birth of Christ, this charming inn offers warm Palestinian hospitality in a peaceful setting. Stone-built rooms with handwoven textiles celebrate local craftsmanship.',
    amenities: ['WiFi', 'Parking', 'Garden', 'Halal Kitchen', 'Prayer Room'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
    featured: false,
    phone: '+972-2-2774-555',
    email: 'stay@shepherdsinn.ps',
    policies: 'Check-in: 2:00 PM | Check-out: 11:00 AM | Free cancellation up to 48 hours.',
    rooms: [
      { id: 'r16', type: 'Traditional Room', capacity: 2, bedType: 'Twin', pricePerNight: 110, available: true },
      { id: 'r17', type: 'Family Room', capacity: 4, bedType: 'Queen + Twins', pricePerNight: 180, available: true },
    ],
  },
  {
    id: '8',
    name: 'Jerusalem Gate Suites',
    nameAr: 'أجنحة باب القدس',
    city: 'Jerusalem',
    address: 'Jaffa Road, West Jerusalem',
    stars: 4,
    pricePerNight: 240,
    rating: 4.3,
    reviewCount: 278,
    description: 'Modern suites with kitchen facilities near Jerusalem\'s Mahane Yehuda market and the iconic Jaffa Gate. Perfect for extended stays, offering a residential feel with hotel-quality amenities and easy access to all holy sites.',
    amenities: ['WiFi', 'Gym', 'Room Service', 'Parking', 'City View', 'Restaurant'],
    images: ['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800'],
    featured: true,
    phone: '+972-2-5001-234',
    email: 'reservations@jlmgatesuites.com',
    policies: 'Check-in: 4:00 PM | Check-out: 12:00 PM | 48-hour cancellation policy.',
    rooms: [
      { id: 'r18', type: 'Studio Suite', capacity: 2, bedType: 'Queen', pricePerNight: 240, available: true },
      { id: 'r19', type: 'One Bedroom Suite', capacity: 3, bedType: 'King', pricePerNight: 340, available: true },
    ],
  },
  {
    id: '9',
    name: 'Mount of Olives View Hotel',
    nameAr: 'فندق إطلالة جبل الزيتون',
    city: 'Jerusalem',
    address: 'At-Tur, Mount of Olives, Jerusalem',
    stars: 4,
    pricePerNight: 275,
    rating: 4.7,
    reviewCount: 342,
    description: 'Perched on the Mount of Olives with the most breathtaking view of Jerusalem\'s golden skyline and the Dome of the Rock. Every room faces east toward the Holy City. A truly spiritual experience in a luxury setting.',
    amenities: ['WiFi', 'Restaurant', 'Rooftop Terrace', 'City View', 'Room Service', 'Prayer Room', 'Garden'],
    images: ['https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800'],
    featured: true,
    phone: '+972-2-6275-000',
    email: 'info@mtolivesview.ps',
    policies: 'Check-in: 3:00 PM | Check-out: 12:00 PM | 72-hour cancellation policy for weekends.',
    rooms: [
      { id: 'r20', type: 'Holy City View Room', capacity: 2, bedType: 'Double', pricePerNight: 275, available: true },
      { id: 'r21', type: 'Panorama Suite', capacity: 2, bedType: 'King', pricePerNight: 420, available: true },
      { id: 'r22', type: 'Pilgrim Package Room', capacity: 4, bedType: 'Two Doubles', pricePerNight: 380, available: false },
    ],
  },
  {
    id: '10',
    name: 'Nablus Heritage Inn',
    nameAr: 'نزل نابلس التراثي',
    city: 'Nablus',
    address: 'Old City, Nablus, West Bank',
    stars: 3,
    pricePerNight: 80,
    rating: 4.1,
    reviewCount: 89,
    description: 'In the shadow of Jacob\'s Well and within walking distance of the ancient hammams and soap factories, Nablus Heritage Inn is a restored caravanserai offering authentic stays for the culturally curious traveler.',
    amenities: ['WiFi', 'Halal Kitchen', 'Prayer Room', 'Garden', 'Parking'],
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
    featured: false,
    phone: '+972-9-2381-000',
    email: 'nablusinns@gmail.ps',
    policies: 'Check-in: 2:00 PM | Check-out: 11:00 AM | Free cancellation up to 24 hours.',
    rooms: [
      { id: 'r23', type: 'Heritage Room', capacity: 2, bedType: 'Double', pricePerNight: 80, available: true },
      { id: 'r24', type: 'Courtyard Room', capacity: 2, bedType: 'Twin', pricePerNight: 90, available: true },
    ],
  },
];

export const mockBookings = [
  { id: 'BK001', hotelId: '1', hotelName: 'Dar Al-Sultan Heritage Hotel', city: 'Jerusalem', guestName: 'Ahmad Khalil', guestEmail: 'ahmad@example.com', roomType: 'Deluxe Suite', checkIn: '2025-06-10', checkOut: '2025-06-14', nights: 4, totalPrice: 1920, status: 'CONFIRMED', createdAt: '2025-05-20' },
  { id: 'BK002', hotelId: '2', hotelName: 'Bethlehem Star Hotel', city: 'Bethlehem', guestName: 'Sara Mansour', guestEmail: 'sara@example.com', roomType: 'Superior Room', checkIn: '2025-06-15', checkOut: '2025-06-18', nights: 3, totalPrice: 660, status: 'PENDING', createdAt: '2025-05-21' },
  { id: 'BK003', hotelId: '5', hotelName: 'Jericho Oasis Resort', city: 'Jericho', guestName: 'Michael Chen', guestEmail: 'mchen@example.com', roomType: 'Pool Suite', checkIn: '2025-07-01', checkOut: '2025-07-05', nights: 4, totalPrice: 1800, status: 'CONFIRMED', createdAt: '2025-05-22' },
  { id: 'BK004', hotelId: '3', hotelName: 'Nazareth Palace Hotel', city: 'Nazareth', guestName: 'Lisa Turner', guestEmail: 'lturner@example.com', roomType: 'Classic Room', checkIn: '2025-05-01', checkOut: '2025-05-04', nights: 3, totalPrice: 630, status: 'CANCELLED', createdAt: '2025-04-10' },
  { id: 'BK005', hotelId: '9', hotelName: 'Mount of Olives View Hotel', city: 'Jerusalem', guestName: 'Yusuf Ibrahim', guestEmail: 'yusuf@example.com', roomType: 'Panorama Suite', checkIn: '2025-06-20', checkOut: '2025-06-23', nights: 3, totalPrice: 1260, status: 'CONFIRMED', createdAt: '2025-05-23' },
  { id: 'BK006', hotelId: '6', hotelName: 'Ramallah Cultural Hotel', city: 'Ramallah', guestName: 'Noura Abboud', guestEmail: 'noura@example.com', roomType: 'Art Suite', checkIn: '2025-07-10', checkOut: '2025-07-13', nights: 3, totalPrice: 690, status: 'PENDING', createdAt: '2025-05-24' },
  { id: 'BK007', hotelId: '8', hotelName: 'Jerusalem Gate Suites', city: 'Jerusalem', guestName: 'David Levy', guestEmail: 'dlevy@example.com', roomType: 'One Bedroom Suite', checkIn: '2025-08-01', checkOut: '2025-08-07', nights: 6, totalPrice: 2040, status: 'CONFIRMED', createdAt: '2025-05-25' },
  { id: 'BK008', hotelId: '4', hotelName: 'Al-Khalil Grand Hotel', city: 'Hebron', guestName: 'Fatima Naser', guestEmail: 'fatima@example.com', roomType: 'Standard Room', checkIn: '2025-04-15', checkOut: '2025-04-17', nights: 2, totalPrice: 190, status: 'CANCELLED', createdAt: '2025-04-01' },
  { id: 'BK009', hotelId: '7', hotelName: "Beit Sahour Shepherd's Inn", city: 'Bethlehem', guestName: 'Robert Hill', guestEmail: 'rhill@example.com', roomType: 'Family Room', checkIn: '2025-12-22', checkOut: '2025-12-27', nights: 5, totalPrice: 900, status: 'CONFIRMED', createdAt: '2025-05-26' },
  { id: 'BK010', hotelId: '10', hotelName: 'Nablus Heritage Inn', city: 'Nablus', guestName: 'Amira Hasan', guestEmail: 'amira@example.com', roomType: 'Heritage Room', checkIn: '2025-06-05', checkOut: '2025-06-07', nights: 2, totalPrice: 160, status: 'PENDING', createdAt: '2025-05-27' },
  { id: 'BK011', hotelId: '1', hotelName: 'Dar Al-Sultan Heritage Hotel', city: 'Jerusalem', guestName: 'Carlos Mendez', guestEmail: 'carlos@example.com', roomType: 'Standard Room', checkIn: '2025-09-10', checkOut: '2025-09-14', nights: 4, totalPrice: 1280, status: 'CONFIRMED', createdAt: '2025-05-28' },
  { id: 'BK012', hotelId: '2', hotelName: 'Bethlehem Star Hotel', city: 'Bethlehem', guestName: 'Emma Wilson', guestEmail: 'emma@example.com', roomType: 'Standard Room', checkIn: '2025-12-24', checkOut: '2025-12-28', nights: 4, totalPrice: 720, status: 'CONFIRMED', createdAt: '2025-05-29' },
  { id: 'BK013', hotelId: '3', hotelName: 'Nazareth Palace Hotel', city: 'Nazareth', guestName: 'Hassan Jabra', guestEmail: 'hassan@example.com', roomType: 'Junior Suite', checkIn: '2025-07-20', checkOut: '2025-07-25', nights: 5, totalPrice: 1750, status: 'PENDING', createdAt: '2025-05-30' },
  { id: 'BK014', hotelId: '5', hotelName: 'Jericho Oasis Resort', city: 'Jericho', guestName: 'Sophie Laurent', guestEmail: 'sophie@example.com', roomType: 'Garden View Room', checkIn: '2025-03-10', checkOut: '2025-03-13', nights: 3, totalPrice: 885, status: 'CANCELLED', createdAt: '2025-02-20' },
  { id: 'BK015', hotelId: '9', hotelName: 'Mount of Olives View Hotel', city: 'Jerusalem', guestName: 'Ibrahim Saleh', guestEmail: 'ibrahim@example.com', roomType: 'Holy City View Room', checkIn: '2025-10-01', checkOut: '2025-10-05', nights: 4, totalPrice: 1100, status: 'CONFIRMED', createdAt: '2025-05-31' },
  { id: 'BK016', hotelId: '6', hotelName: 'Ramallah Cultural Hotel', city: 'Ramallah', guestName: 'Maria Garcia', guestEmail: 'maria@example.com', roomType: 'Standard Room', checkIn: '2025-08-15', checkOut: '2025-08-18', nights: 3, totalPrice: 465, status: 'CONFIRMED', createdAt: '2025-06-01' },
  { id: 'BK017', hotelId: '8', hotelName: 'Jerusalem Gate Suites', city: 'Jerusalem', guestName: 'Omar Barakat', guestEmail: 'omar@example.com', roomType: 'Studio Suite', checkIn: '2025-11-01', checkOut: '2025-11-04', nights: 3, totalPrice: 720, status: 'PENDING', createdAt: '2025-06-02' },
  { id: 'BK018', hotelId: '4', hotelName: 'Al-Khalil Grand Hotel', city: 'Hebron', guestName: 'Anna Petrov', guestEmail: 'anna@example.com', roomType: 'Double Room', checkIn: '2025-09-05', checkOut: '2025-09-08', nights: 3, totalPrice: 360, status: 'CONFIRMED', createdAt: '2025-06-03' },
  { id: 'BK019', hotelId: '7', hotelName: "Beit Sahour Shepherd's Inn", city: 'Bethlehem', guestName: 'James O\'Brien', guestEmail: 'james@example.com', roomType: 'Traditional Room', checkIn: '2025-04-12', checkOut: '2025-04-15', nights: 3, totalPrice: 330, status: 'CANCELLED', createdAt: '2025-03-20' },
  { id: 'BK020', hotelId: '10', hotelName: 'Nablus Heritage Inn', city: 'Nablus', guestName: 'Layla Mahmoud', guestEmail: 'layla@example.com', roomType: 'Courtyard Room', checkIn: '2025-07-08', checkOut: '2025-07-11', nights: 3, totalPrice: 270, status: 'CONFIRMED', createdAt: '2025-06-04' },
];

export const MOCK_USER = {
  id: 'u1',
  name: 'Ahmad Khalil',
  email: 'ahmad@example.com',
  role: 'GUEST',
};

export const MOCK_ADMIN = {
  id: 'u2',
  name: 'Admin User',
  email: 'admin@terrastay.ps',
  role: 'ADMIN',
};
